name: Remixing the app 💿

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: brew install make ldid dpkg

      - name: Set environment
        run: |
          echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH
          echo "THEOS=${{ github.workspace }}/theos" >> $GITHUB_ENV

      - name: Setup Theos
        uses: actions/checkout@v4
        with:
          repository: theos/theos
          path: theos
          submodules: recursive

      - name: Download iOS SDK
        run: |
          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/theos/sdks.git
          cd sdks
          git sparse-checkout set --no-cone iPhoneOS16.5.sdk
          git checkout
          mv *.sdk $THEOS/sdks

      - name: Build rootless package
        run: make clean package DEBUG=0 FINALPACKAGE=1

      - name: Upload .deb
        uses: actions/upload-artifact@v4
        with:
          name: BetterLyricsYTM-deb
          path: packages/*.deb
